version: '3.9'
services:
    users:
        image: 'nyos777/user-service-dev'
        container_name: 'nyos-user'
        ports:
            - '8082:8082'
        restart:
            always
        depends_on:
            - nyos-db
            - minio
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://nyos-db/messagesDB
            - SPRING_DATASOURCE_USERNAME=nyos
            - SPRING_DATASOURCE_PASSWORD=purple
            - SPRING_MINIO_URL=http://localhost:9000
            - SPRING_MINIO_ACCESS_KEY=nyos
            - SPRING_MINIO_SECRET_KEY=nyos7777
            - FILE-SYSTEM-SERVICE=http://files:8081
        networks:
            - nyos_net
    files:
        image: 'nyos777/file-service-dev'
        container_name: 'nyos-file'
        ports:
            - '8081:8081'
        restart:
            always
        depends_on:
            - nyos-db
            - minio
            - users
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://nyos-db/messagesDB
            - SPRING_DATASOURCE_USERNAME=nyos
            - SPRING_DATASOURCE_PASSWORD=purple
            - SPRING_MINIO_URL=http://minio:9000
            - SPRING_MINIO_ACCESS_KEY=nyos
            - SPRING_MINIO_SECRET_KEY=nyos7777
        networks:
            - nyos_net
    nyos-db:
        image: 'postgres:14.11'
        container_name: 'nyos-postgres'
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=nyos
            - POSTGRES_PASSWORD=purple
            - POSTGRES_DB=messagesDB
        restart: always
        networks:
            - nyos_net
        volumes:
            - nyos_db_data_pub:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - '8080:8080'
        networks:
            - nyos_net
    minio:
        image: quay.io/minio/minio
        command: server /data --console-address ":9090"
        restart: always
        ports:
            - '9000:9000'
            - '9090:9090'
        volumes:
            - ~/minio/data:/data
        environment:
            - MINIO_ROOT_USER=nyos
            - MINIO_ROOT_PASSWORD=nyos7777
        networks:
            - nyos_net
networks:
    nyos_net:

volumes:
    nyos_db_data_pub:
