version: '3.9'
services:
  nyos-db:
    image: 'postgres:14.11'
    container_name: 'nyos-postgres'
    environment:
      - POSTGRES_USER=nyos
      - POSTGRES_PASSWORD=purple
      - POSTGRES_DB=messagesDB
    ports:
    - '5432:5432'
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=nyos
      - MINIO_ROOT_PASSWORD=nyos7777
    networks:
      - minio_net
networks:
  minio_net:
