server:
    port: ${SERVER_PORT:8082}

spring:
    servlet:
        multipart:
            max-request-size: 50MB
            max-file-size: 50MB
    main:
        banner-mode: off
    jpa:
        show-sql: true
#        open-in-view: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        #                jdbc:
#                    batch_size: 20
#                batch_versioned_data: true
#                order_inserts: true
#                order_updates: true
#                generate_statistics: ${HIBERNATE_GENERATE_STATISTICS:false}
#                dialect: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/messagesDB}
        username: ${DATASOURCE_USERNAME:nyos}
        password: ${DATASOURCE_PASSWORD:purple}
        driver-class-name: org.postgresql.Driver
    rabbitmq:
        host: ${RABBIT_HOST:localhost}
        port: ${RABBIT_PORT:5672}
        username: ${RABBIT_USERNAME:nyos}
        password: ${RABBIT_PASSWORD:purple}
service:
    file-system-service:
        url: ${FILE-SYSTEM-SERVICE:http://localhost:8081}

